#!/bin/bash


. ./config


echo "
[SAN]
 subjectAltName=$EXTERNAL_IP
" > /tmp/oneused



#герерация ключа
openssl genrsa -out /etc/ssl/certs/root-ca.key 2048

#генерация корневого сертификата
openssl req -x509 -new -key /etc/ssl/certs/root-ca.key -days 365 -out /etc/ssl/certs/root-ca.crt \
-subj "/C=UA/ST=Kharkov/L=Kharkov/O=Student/CN=noob.studio"

#генерируем сертификат, подписанный нами же
openssl genrsa -out /etc/ssl/certs/selfCA.key 2048

#генерим запрос на сертификат
openssl req -new -newkey rsa:4096 -key /etc/ssl/certs/selfCA.key \
-out /etc/ssl/certs/web.csr \
-subj "/C=UA/ST=Kharkov/L=Kharkov/O=Student/CN=$(hostname -f)" \
-reqexts SAN -extensions SAN -config <(cat /etc/ssl/openssl.cnf /tmp/oneused)


#подписываем запрос на сертификат
openssl x509 -req -in /etc/ssl/certs/web.csr -CA /etc/ssl/certs/root-ca.crt -CAkey /etc/ssl/certs/root-ca.key \
-CAcreateserial -out /etc/ssl/certs/web.crt -days 100 -extensions SAN -extfile /tmp/oneused

cat /etc/ssl/certs/web.crt  /etc/ssl/certs/root-ca.crt > /etc/ssl/certs/$(hostname -f).crt



